# Generated by Django 4.2.14 on 2024-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_remove_mailing_actual_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Активна"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
